version: '3'

volumes:
  shopsystem_mysql:

services:
  shopsystem_db:
    container_name: sf_mysql
    image: "mariadb:10.5"
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=shopsystem
      - MYSQL_USER=shopsystem
      - MYSQL_PASSWORD=shopsystem
      - TZ=Europe/Warsaw
    volumes:
      - shopsystem_mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    container_name: sf_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './:/usr/src/app'
    user: ${LOCAL_USER}

  nginx:
    container_name: sf_nginx
    image: nginx:latest
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
